sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.11.11
  - 2.12.7
  - 2.13.0-M4

jdk:
  - oraclejdk8

script:
  - node -v
  - sbt ++$TRAVIS_SCALA_VERSION "project coreJVM" test mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION "project testkitJVM" test mimaReportBinaryIssues

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
